name: Build for Mac

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-mac-app:
    name: Release Mac
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 macOS
        continue-on-error: true

      - name: Build Mac
        run: |
          flutter build macos --release --dart-define-from-file=jimi_release.json

      - name: Prepare Upload
        run: |
          npm install --global create-dmg
          create-dmg build/macos/Build/Products/Release/哈基密码本.app || true
        continue-on-error: true

      - name: Rename DMG
        run: mv 哈基密码本*.dmg hajimiPass_macos_${{ inputs.tag }}.dmg

      - name: Release
        if: ${{ inputs.tag != '' && !contains(inputs.tag, 'test') }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          draft: true
          prerelease: true
          files: |
            hajimiPass_macos_${{ inputs.tag }}.dmg

      - name: Upload macos release
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: macOS-release
          path: hajimiPass_macos_*.dmg
